### ISSUE TITLE
fonctionnement des potar?

### ISSUE THREAD

**Issue by JePica** [Sercurio/BT110_public#16]
je sait pas si c'est moi mais je trouve ca un peut bizard de devoir clicker le potar pour ce déplacer rapidement, 
car c'est pas hyper facile de tourné la pot en etan appuyer,

 je pense que potar appuyer devrais être -> un déplacement de précision
potar qui tourne pas vite -> déplacement normal (genre comme un vrais pot)
potar qui tourne vite ->déplacement rapide

**Comment by Sercurio** [comment]
Si on compare au workflow du Digitakt, lors de l'édition d'un sample:
potard qui tourne normal -> précision 
potard appuyer -> rapide

Est ce que tu pense que ta proposition une plus-value dans l'un des écrans ?

**Comment by JePica** [comment]
non je pense qu'on peut oublier mon idée:)
