### ISSUE TITLE
bug mode editor

### ISSUE THREAD

**Issue by JePica** [Sercurio/BT110_public#2]
j'ai eu un bug dans le mode editor après avoir essayer de rentrer une fonction de deux ligne avec des f(x) , je ne sait pas pourquoi a un moment les insers de caractère genre parenthèse et t ne marchais plus et ne fessais que effacer la fonction, 
je n'est pas réssuie a recréer ce bug

**Comment by Sercurio** [comment]
Yes j'ai déja eu le probleme, je vais tenter de reproduire

**Comment by Sercurio** [comment]
fixed
