### ISSUE TITLE
besoin de carractère manquant?

### ISSUE THREAD

**Issue by JePica** [Sercurio/BT110_public#3]
sur les site de bytebeat il y a des formule du genre : 

((t*("36364689"[t>>13&7]&15))/12&128)+(((((t>>12)^(t>>12)-2)%11*t)/4|t>>13)&127)

mais on peut pas le faire car on a pas "" et [ ] .

mais je sait pas si c'est nécessaire et /ou faisable

**Comment by Sercurio** [comment]
Je pense que tu as regardé dans la partie JS non ?
Pour moi, il manque seulement la possibilité de faire du ternaire "t ? 1 : 0"
Ensuite les crochets seront surement utilisés pour gérer deux formules avec cette sorte de syntaxe: "[formula1, formula2]"

**Comment by JePica** [comment]
je sait pas je l'ai trouver [ici ](https://bytebeat.demozoo.org/#t=0&e=0&s=11025&bb=5d0000010094000000000000000017e07caa6ebfa03f46f57ac990ba22829c07271614ceb006194a2f5a28a868904edcbc4ff804a942bf0ae46ff3850557cf9369db58fb7b66f9c8bf069708400cd92737f9064830de2cdfde4f855031c041c0ee55c1d5ab7cd0155dc113bab3866a1fc25511c251834cb3c6171a7d270a66736fe97a5645851fda76172a95aaf316d3b616bac11fff425e0000)


Unnecessary-ARPEG
// by: lhphr
// from: https://dollchan.net/btb/res/3.html#44

dans les bytebeat infix small

**Comment by Sercurio** [comment]
Les chaines de caractères et les tableaux de valeur ne sont pas dans le scope du bytebeat C
