### ISSUE TITLE
sequencer nove up down issue

### ISSUE THREAD

**Issue by JePica** [Sercurio/BT110_public#4]
trop bien la nouvelle manière de ce ballader dans le sequencer 
avec le fn pour le quick replace et le yes pour l'accès au formules saved 👍 

par contre il y a un bug entre le up et down pour aller du pas 8 a 16 et du pas 9 a 1 

et aussi dans le menu quick assign quand on fait up down il faudrait plutôt utiliser le fonction user plutôt que les static au trouver u moyen de passe d'un bank a l'autre  genre avec mode mais c'est peut etre chaud

**Comment by Sercurio** [comment]
Ok pour le bug, je vais checker ça

Au niveau du quick assign, j'avais pensé à utiliser yes(1) pour les userFormulas et no(3) pour les staticFormulas, qu'est ce que tu en dis ?

**Comment by JePica** [comment]
peut etre function + mode qui toggle de user a static

comme ca tu garde function yes pour save la sequence dans le future:)

**Comment by JePica** [comment]
comme ca tu garde function yes pour save la sequence dans le future:)
