### ISSUE TITLE
bug au chargement d'une phrase vide

### ISSUE THREAD

**Issue by JePica** [Sercurio/BT110_public#5]
quand on fait mode +editor et qu'on va dans saved formulas, si on charge une formules vide il peut y avoir quand même des bout de formule qui traine.

après en réfléchissant ce doit être un bug du au fait que j'ai utilisé une autre version du soft et que du coup j'avais encor des  bout de formule dans l'eeprom

**Comment by Sercurio** [comment]
Pas reproduit a l'heure d'aujourd'hui
