### ISSUE TITLE
changement de type sybole automatique

### ISSUE THREAD

**Issue by JePica** [Sercurio/BT110_public#6]
Dans le mode editor, ca serrais cool, que le mode (f(x) +-x 123) change automatiquement en fonction de ce qui est présent initialement.

et après on peut toujours re changer le mode avec le bouton mode

**Comment by Sercurio** [comment]
Si jamais le curseur est sur un espace, t, ou une parenthèse (caractères non listés dans les tableaux de symboles) 
Que se passe t'il ?

**Comment by JePica** [comment]
on change pas de type de fonction, on reste dans celle précédemment sélectionner
